### PR TITLE
upgrade to rspec 3

### LINKED ISSUE #4: upgrade for rspec 3

### PR DESCRIPTION
**Pull request by tampakis**
Closes #4.

### CODE REVIEW

**Comment by tampakis** [comment]
@ndushay does this look ok?

**Comment by cbeer** [comment]
:+1: from me. I've been trying to think of a better way to do the `raise_error.with_message` matcher without the ugly escaping, but haven't come up with anything yet.

**Comment by tampakis** [comment]
I agree that it's pretty nasty. I could go back to the 'fail_matching' syntax, which is still used in their tests:
https://github.com/rspec/rspec-expectations/blob/aae135783a860ccccd4257880e8b6b71ea02d8cb/spec/rspec/matchers/built_in/include_spec.rb

**Comment by cbeer** [comment]
Actually, can we do:

```ruby
expect { }.to raise_error.with_message a_string_matching '} to include {"not_there" => "anything"}'
```

?

**Comment by tampakis** [comment]
Yeah that would work. I'll update the pull request.

**Comment by tampakis** [comment]
Most of the ugly escaping is still needed with `a_string_matching` for brackets and the `"id" => /\d{3}/` regex so maybe it still makes sense to use `fail_matching` after the `expect { }.to` block?

**Comment by tampakis** [comment]
I updated my commit. I avoided the character escapes using the `a_string_including` matcher
I updated the other tests to not rely on `fail`, `fail_with`, `fail_matching` at all.

**Comment by tampakis** [comment]
The include [perform_match](https://github.com/rspec/rspec-expectations/blob/master/lib/rspec/matchers/built_in/include.rb#L67-L88) method was updated in rspec 3.3 (upgraded on Travis literally in the past week) so I needed to update the override yet again.

**Comment by cbeer** [comment]
:+1: Can you squash the commits down and then I'll merge it?

**Comment by tampakis** [comment]
Squashed.

**Comment by jpstroop** [comment]
@cbeer @ndushay :squirrel::question: We're happy to keep using our fork, but if there's something else you'd like to see here, feel free to let @tampakis know.

**Comment by cbeer** [comment]
Thanks. I've cleaned up a couple more things and released v2.0.0

**Comment by tampakis** [comment]
Nice!

**Comment by ndushay** [comment]
:+1:   Sorry - I meant to get to this and got distracted.  Thanks @cbeer

**Pull request merged**
